### ISSUE TITLE
Difficult to generate docs reliably

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#109]
We chose to use jsdoc style for the initial release. Unfortunately, I've had issues generating jsdocs from typescript code and from the generated JavaScript. Instead, I tried using Typedoc, and while this at least allows me to generate documentation, the documentation is not good for our end users. 

For example, if I want to generate docs for the `db` package, I need to exclude a million specific things (such as the constructor because the end user never "constructs" a db instance). I've attempted to do this manually, but I believe it's a flawed approach for two main reasons:

1. My process breaks whenever a change is made to the API
2. It's easier for engineering to understand what is/isn't important as opposed to an external judge

We need a method that allows engineering to concisely expose the API (and docs) that will be directly relevant for the end user.

**Comment by vogre** [comment]
May be an obvious question, but did you use `--excludeNotExported` when using typedoc?

Re: constructor, I think latest spec required a constructor.

I've looked previously at typedoc and on documentation of various frameworks, and found that the frameworks usually have hand-crafted documentation which makes chronological sense to a newcomer and generated docs are of secondary priority or not featured at all.

**Comment by arielshaqed** [comment]
I'm closing this as fixed by #237.  Please re-open if you disagree.

**Comment by arielshaqed** [comment]
Also #20.
