### ISSUE TITLE
Make sure lint enforces space padding for curly braces

### ISSUE THREAD

**Issue by bergundy** [reshufflehq/reshuffle#123]
`{a: 1}` should fail lint.
`{ a: 1 }` should pass.

**Comment by vogre** [comment]
`tslint` has a `check-postbrace` rule, which almost works, but doesn't since it doesn't allow `{}` empty objects.

Maybe it's time to evaluate `typescript-eslint`.

**Comment by arielshaqed** [comment]
> Maybe it's time to evaluate `typescript-eslint`.

Yes.  `tslint` is going away.  Please don't waste time solving this on `tslint`.
