### ISSUE TITLE
multiple shift_local_proxy folders on windows

### ISSUE THREAD

**Issue by zolga** [reshufflehq/reshuffle#132]
A new folder is created on every npm start, without removing the old one.

d-----         8/7/2019   3:03 PM                .shift_local_proxy_XPMhye
d-----         8/2/2019  12:59 PM                .shift_local_proxy_xPoKzI
d-----         8/6/2019  10:17 PM                .shift_local_proxy_xtBJsu
d-----         8/2/2019   3:47 PM                .shift_local_proxy_Xx00XP
d-----         8/2/2019  12:54 PM                .shift_local_proxy_XZw81G
d-----         8/7/2019  12:58 AM                .shift_local_proxy_yd6433
d-----         8/2/2019   3:43 PM                .shift_local_proxy_yEph4q
d-----         8/6/2019   5:43 PM                .shift_local_proxy_yFEtKG
d-----         8/2/2019   3:02 PM                .shift_local_proxy_yIx3Yq
d-----         8/2/2019  12:55 PM                .shift_local_proxy_YKooti
d-----         8/2/2019  11:26 PM                .shift_local_proxy_yOFNbK
d-----         8/6/2019  11:38 PM                .shift_local_proxy_YOwEnQ
d-----         8/2/2019  12:50 PM                .shift_local_proxy_ypn612
d-----         8/7/2019  12:44 AM                .shift_local_proxy_Yq9k0r
d-----         8/7/2019  12:15 AM                .shift_local_proxy_YRYbIf
d-----         8/7/2019  12:48 AM                .shift_local_proxy_YT9Ef2
d-----         8/1/2019  10:09 AM                .shift_local_proxy_Z9Gll6
d-----         8/3/2019  12:19 AM                .shift_local_proxy_ZaPdvo
d-----         8/7/2019  12:49 AM                .shift_local_proxy_ZBddS2
d-----         8/7/2019  12:27 AM                .shift_local_proxy_zEY9N7
d-----         8/6/2019  11:41 PM                .shift_local_proxy_zFVzz1
d-----         8/2/2019  12:59 PM                .shift_local_proxy_ZG6fwl
d-----         8/2/2019  11:09 PM                .shift_local_proxy_ZJ9bXJ
d-----         8/1/2019  11:02 PM                .shift_local_proxy_Zmrr1I
d-----         8/2/2019  12:50 PM                .shift_local_proxy_Zn10c4
d-----         8/7/2019  12:50 AM                .shift_local_proxy_zo8RVm
d-----         8/6/2019  11:44 PM                .shift_local_proxy_ZpoksV
d-----         8/2/2019  11:11 PM                .shift_local_proxy_zpyRMx
d-----         8/7/2019  12:49 AM                .shift_local_proxy_Zuyjfs
d-----         8/7/2019   9:36 PM                .shift_local_proxy_zXyGuh
d-----         8/5/2019   9:24 AM                .shift_local_proxy_zzOu90

**Comment by michaeladda** [comment]
embedding code into the `process.once` handlers in `local-proxy/src/server.ts` the handlers are called, but rimraf never returns
