### ISSUE TITLE
CLI config should be placed in a "better" location

### ISSUE THREAD

**Issue by bergundy** [reshufflehq/reshuffle#137]
Currently `~/.shiftjs/shiftjs.config.yml`.
We should probably use the system's config dir or at least just call it `~/shiftjs/config.yml`.

**Comment by bergundy** [comment]
CC @arikmaor @rylandg

**Comment by vogre** [comment]
Would definitely prefer being a nice citizen and respecting [XDG_CONFIG_HOME](https://wiki.archlinux.org/index.php/XDG_Base_Directory), so by default `~/.config/shiftjs/...`.

There are varying opinions on locations in MacOS (https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) and %LOCALAPPDATA% on Windows.

**Comment by rylandg** [comment]
Hey. I'm relatively un-opinionated. The most common way is obviously a hidden folder in `/home/` although as Vlad mentioned, a lot of people are frustrated by that. I would prefer whatever option is most intuitive to our users.
