### ISSUE TITLE
[Windows] Local database lock file gets into borked state

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#163]
We've now had two instances where users running on Windows encountered a situation that seriously blocked their ability to continue developing. Other than being on Windows and using a slightly old (same dependency versions as my [poll app](https://github.com/shiftjs/poll)) version of the template template.

The user was able to develop initially with the project, but at some point it became impossible to move forward. The following error is presented in the console.

![screen4error copy](https://user-images.githubusercontent.com/27736122/63613913-a07fb100-c596-11e9-8901-b03bc34be58d.png)

Having encountered this error before (with @zolga on her Windows computer), it's very difficult to fix. I could not identify the process that was allegedly writing to the file, such as a duplicate server. After trying a ton of different solutions, we eventually resorted to a restart which may have helped but did not fix the problem in its own right. In Olgas case, we eventually identified that there was a package version mismatch that had occurred during a manual upgrade.

This is not  the case with the user who encountered the error today. The user sent me his non-working project and I am able to run it both on OSX and Linux without issue. His dependencies are not mis-aligned, they are at the exact versions used by my `poll` app.  A restart did not fix the issue.

**Comment by vogre** [comment]
This is no confirmation, but the DB architecture changed significantly in [local-proxy 0.2.0](https://github.com/binaris/shiftjs/blob/master/local-proxy/CHANGELOG.md#020) - need to watch if bug ever reproduces after.

**Comment by michaeladda** [comment]
@rylandg please reproduce or close
