### ISSUE TITLE
According to CLI, everyone is Ariel

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#225]
```
npx: installed 140 in 9.171s
deploy your Reshuffle project to its associated domain

USAGE
  $ reshuffle deploy

OPTIONS
  -h, --help       show CLI help
  --config=config  [default: /Users/ariels/.reshuffle/config.yml]

EXAMPLE
  $ reshuffle deploy
```
I'm not sure if its supposed to be an example ( I would add `eg:`) or just a mistake.

**Comment by rylandg** [comment]
###

**Comment by arielshaqed** [comment]
It's "last builder wins" over there. oclif is weirdly broken. We'll fix it,
but if you want to you can have your turn just by publishing the next
version!

**Comment by rylandg** [comment]
That is an amazing bug from oclif. Thanks for the quick response.
