### ISSUE TITLE
Deployment succeeds but app is broken

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#227]
After upgrading to use `@reshuffle` instead of shift, I tried to deploy my project. The deployment went through, but when I go to the URL my app is broken:

```
{"error":"Cannot find module '/code/node_modules/@reshuffle/server-function/dist/serveBinaris.js'","stack":"Error: Cannot find module '/code/node_modules/@reshuffle/server-function/dist/serveBinaris.js'\n    at Function.Module._resolveFilename (module.js:548:15)\n    at Function.Module._load (module.js:475:25)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Bolt.requireUserFunction (/opt/binaris/dist/bolt.js:87:24)\n    at <anonymous>"}
```

The logs only display the above error:

```
{ Error: Cannot find module '/code/node_modules/@reshuffle/server-function/dist/serveBinaris.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Bolt.requireUserFunction (/opt/binaris/dist/bolt.js:87:24)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

I doubt it's anything specific to my project, but I have not tried deploying a project from scratch to see if it works.

**Comment by michaeladda** [comment]
please share `package.json`, `package-lock.json`, and `ls -l node_modules/\@reshuffle/server-function/dist/`.
Specifically, do you have `@reshuffle/server-function` version `0.0.6` as a dep in both?
did you `npm install`?

**Comment by rylandg** [comment]
I did have all of the dependencies upgraded.

https://github.com/binaris/dev-docs/tree/update-deps

That is the tree I was using when I tried. I also tried recreating my Reshuffle project (via the CLI), relogging-in and more. I do not have the same `node_modules` state as I did when the error occurred, but at the time I explicitly checked if my `node_modules` had the `dist/serveBinaris.js` and it did!

**Comment by rylandg** [comment]
Also, I was consistently running locally throughout this process which I believe also utilizes the `serveBinaris.js` file

**Comment by vogre** [comment]
It is not enough to have the file, the package `@reshuffle/server-function` must be in the `package.json` dependencies list.

**Comment by rylandg** [comment]
This is a change correct? I don't believe it was explicitly listed before.

**Comment by rylandg** [comment]
That indeed fixed it. Thanks for the info!
