### ISSUE TITLE
cli: deploy includes packages which are only needed for build

### ISSUE THREAD

**Issue by vogre** [reshufflehq/reshuffle#257]
Including a package like `react-bootstrap` pulls a package of `babel-runtime` and including it in upload makes it considerably heavier. A list of packages to exclude might help, but a different approach for selecting dependencies to upload may be needed.

**Comment by arielshaqed** [comment]
Thing is, it's legit (even likely) for a deployment to rely on `react-bootstrap`.

Let's see how some tree-shakers do it?
