### ISSUE TITLE
Removing older apps seems problematic

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#277]
Both @ashevat and I have older apps (with long 20+ length UUID names instead of the new names) that we would like to remove from our account. When attempting to remove them via the Reshuffle CLI, we receive the following error.

```
 ✘ ubuntu  ~  npx reshuffle destroy 05351db2-xxxx-4942-a47f-xxxxxxxxxxxxxx
     npx: installed 141 in 9.482s
 ›   Error: Function not found
```

At first I thought this was the generic "Does not exist" error, but then I realized it's different when I ran destroy with an app name that really doesn't exist.

```
 ✘ ubuntu  ~  npx reshuffle destroy 765459879-05351db2-xxxx-4942-a47f-xxxxxxxxxxxxxx
     npx: installed 141 in 9.064s
 ›   Error: Application with name 765459879-05351db2-xxxx-4942-a47f-xxxxxxxxxxxxxx
 ›   does not exist
```

The question is, how do we go about removing these old apps?

**Comment by vogre** [comment]
This is an issue which is caused by internal renaming of the function name and not storing it. 

The: `Error: Function not found` means the application was already destroyed successfully - you should not be seeing it in the list anymore - and the only thing left is to GC the orphaned functions.

**Comment by rylandg** [comment]
Thanks for the update! Indeed they are no longer there when running list.
