### ISSUE TITLE
Destroy does not ask for app name when provided no args

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#278]
When attempting to run:

`reshuffle destroy`

without providing an app name, we do not receive an error indicating that the lack of an app name is the problem. Instead we receive the following semi-cryptic error.

```
ubuntu  ~  npx reshuffle destroy
npx: installed 141 in 9.902s
 ›   Error: Could not find a relevant package.json file
```

It would be much easier on the user if we informed them about both options.

**Comment by michaeladda** [comment]
This is working as intended. From the help page:
```
destroy an application

USAGE
  $ reshuffle destroy [ID]

ARGUMENTS
  ID  Application id (defaults to working directory's deployed application ID)
```
If the working directory is not a reshuffle app, an error is printed (which can be improved)
