### ISSUE TITLE
Directory comparison on windows should be case-insensitive

### ISSUE THREAD

**Issue by vogre** [reshufflehq/reshuffle#294]
https://github.com/reshufflehq/reshuffle/blob/8db759cb9d424fc71e5ea24c087aa3c9e075bb8c/cli/src/commands/deploy.ts#L194

Drive letter can be `C:` or `c:` depending on `cwd`

**Comment by arielshaqed** [comment]
Also, for added lulz, on some (but not all) Macs is case insensitive APFS. So there is no simple path comparison. I think the best you can do is `stat` each path and look

**Comment by bergundy** [comment]
All directory comparisons should go through this function:
https://github.com/reshufflehq/reshuffle/blob/8aab567eb0ab4a5e4ecd6433d05644dccac7101e/cli/src/utils/helpers.ts#L13
