### ISSUE TITLE
getCurrentUser can return incorrect information

### ISSUE THREAD

**Issue by michaeladda** [reshufflehq/reshuffle#386]
In `server-function/src/invoke.ts` the variable `currentUser` is stored without the request context, so multiple concurrent requests can get incorrect information. For example, a backend function awaiting a call to another will afterwards get `undefined` from `getCurrentUser`.

**Comment by michaeladda** [comment]
duplicate of https://www.notion.so/reshuffle/Calling-getCurrentUser-more-than-once-throws-Authentication-required-error-a1fad757f9e44cb1b8aeed5572af6fab

**Comment by vogre** [comment]
Thanks for the report!

The design of getCurrentUser is very fragile and relies on calling getCurrentUser before calling any async code (awaiting a promise) https://github.com/reshufflehq/reshuffle/blob/%40reshuffle/server-function_v0.2.2/server-function/src/index.ts

Unfortunately there's no reliable way to make getCurrentUser work in it's current form, an alternative might be to pass this context bound to this in the handler function, or changing the signature of the functions to include a context parameter (e.g. marked by `@expose(context=true)`)

Note that the function has a guarantee to always err on the side of returning `undefined` (unauthenticated) if called not at the beginning of a function -- making an assumption that user code will just error out / reject the request. A function is at all times guaranteed to _not_ get information from a concurrent invocation.

**Comment by vogre** [comment]
A user can always write

```
if (getCurrentUser() === undefined) launchNuclearMissiles();
```

And then us returning an incorrect answer will still be bad, but we assume that most code will not be of this form.
