### ISSUE TITLE
Mismatch readme/code in environment variable for health check path

### ISSUE THREAD

**Issue by cunger** [reshufflehq/reshuffle#482]
The README says:
```
When setting environment variable HEALTH_CHECK_PATH [...]
```

But the code checks for RESHUFFLE_HEALTH_PATH:

https://github.com/reshufflehq/reshuffle/blob/59caf291537c884b9359810548b01cfc6739506f/src/Reshuffle.ts#L105

**Comment by duckranger** [comment]
Thanks @cunger.

#483
