### ISSUE TITLE
A couple of website image glitches

### ISSUE THREAD

**Issue by TomGranot** [reshufflehq/reshuffle#487]
Hey - this looks like a really cool product!

Note that there are a few logo backgrounds left uncleaned in the home page: 

<img width="678" alt="re·shuffle" src="https://user-images.githubusercontent.com/8835035/108390978-df3d0880-7219-11eb-9f55-2337bc3578ed.png">

**Comment by TomGranot** [comment]
@zacmos ping

**Comment by gabeeden** [comment]
@TomGranot thanks, the fix is now live!
