### ISSUE TITLE
@expose leading comment seems risky

### ISSUE THREAD

**Issue by arikmaor** [reshufflehq/reshuffle#49]
consider this code:
```js
// @expose
export function foo() {
}

// @expose
export function bar() {
}

export function internalFunction() {
}
```

turning to this cause function was commented out:
```js
// @expose
export function foo() {
}

// @expose
// export function bar() {
// }
//
export function internalFunction() {
}
```

suddenly internalFunction is exposed!

**Comment by arikmaor** [comment]
maybe we should check only the last line in the comment

or

use something else then the comment

**Comment by arielshaqed** [comment]
> maybe we should check only the last line in the comment

Please don't.  This doesn't even scale to *2* such annotations.  E.g. suppose I write a module `arielogs` that also exposes its decornotation in a "last line contains a comment".  Then the two don't work together.

This is pretty much a solved problem.  I don't think we should innovate here.  We should do what others do: decorators or JSDoc annotations (or maybe something else that others do).

E.g., IIUC JSDoc comments mitigate this: if you line-comment out a JSDoc you end up with the non-JSDoc (and therefore nonexposing)
```js
// /**
//  * @expose
//  */
```

Similarly, the existing [decorators proposal](https://github.com/tc39/proposal-decorators) is pretty safe and people will understand it (sure, you can comment-out a function but not its decorator, but you could equally-well comment out the end of a function and the start of the next function...).  It's not ready yet, but we could probably make use of one of the 2 existing versions it describes in [How does this proposal compare to other versions of decorators?](https://github.com/tc39/proposal-decorators#how-does-this-proposal-compare-to-other-versions-of-decorators).  Code changes would be needed for the `import`s, but at least we get a safe syntax that our users already love.

**Comment by vogre** [comment]
In the `export function` syntax it's possible to change to `export /* @expose */ function`.
