### ISSUE TITLE
Cross platform development is not supported

### ISSUE THREAD

**Issue by arikmaor** [reshufflehq/reshuffle#53]
Currently our projects can be built on linux

They usually can be built in osx but we don't make it a priority (ie. using `cp -r` instead of `cp -R`)

They usually can never be built in windows (things like `cp` and `rm -rf` doesn't work there)

We should make an effort to support all platforms, this includes:
1. Changing all `rm -rf` to `rimraf` npm package.
2. Use `cross-env` to set environment variables in npm scripts
3. Find cross platform alternative to `cp`
4. Probably other stuff, maybe `jenkins` can try to build on windows?

**Comment by vogre** [comment]
Note that Windows development mostly works, the only requirements are:

- [jq](https://stedolan.github.io/jq/)
- [git bash](https://gitforwindows.org/)
