### ISSUE TITLE
Imported backend code does not trigger reload in some cases

### ISSUE THREAD

**Issue by rylandg** [reshufflehq/reshuffle#90]
This is difficult because Amir and I tried our best to consistently reproduce, but were not able to. Amir was developing a very basic MV(-1) app, and was importing backend code using the expected destructuring syntax.

```javascript
import { getBasic, getOtherBasic, getFinal } from '../backend/backend.js';
```

When we could produce the bug, it appeared that adding a new key to destructure, was not enough to trigger a backend update.

```diff
- import { getBasic, getOtherBasic, getFinal } from '../backend/backend.js';
+ import { newAddition, getBasic, getOtherBasic, getFinal } from '../backend/backend.js';
```

I suspect that he used the imported function  before importing it, saved the file. This clearly did not produce a valid build because he was relying on an unimported function. Afterwards, he did import it, but still received the same error.

```
Could not invoke /newAddition
```

Removing the specific imported function immediately removed the issue and the app worked correctly (including other backend functions). After messing around with it, we could not reproduce the generic bug.

**Comment by vogre** [comment]
Please attach the shiftjs version to the report. 

> used the imported function before importing it

This should fail the build / show up as a red error screen. 

The message of `Failed invoke` should contain error info, please provide the full log if you encounter it again.

**Comment by zolga** [comment]
This bug happened to me today, my **shiftjs version** is the following:
    "@binaris/shift-babel-macro": "0.0.3",
    "@binaris/shift-db": "^0.1.2",
    "@binaris/shift-fetch-runtime": "0.0.2",
    "@binaris/shift-local-proxy": "0.0.4",

**Error details:** 
Failed to compile
./src/utils/AuthHelper.js
Error: @binaris/shift-babel-macro/macro: "validateUser" is missing from "../../backend/backend", did you forget to @expose ? Learn more: https://www.npmjs.com/package/@binaris/shift-babel-macro
    at Array.forEach (<anonymous>)
This error occurred during the build time and cannot be dismissed.

**Comment by vogre** [comment]
Changes in backend code do not trigger recompilation of the front-end, if I understand the bug now correctly, it is a missing feature.
